{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "CONTRIBUTOR",
   "body" : "This test failed for me on master locally:\r\nThe reason is that when initiating a v2 connection and being immediately disconnected, a node cannot know if the disconnect happens because the peer only supports v1, or because it has banned you, so it schedules to reconnect with v1. If the test doesn't wait for that, the reconnect can happen at a bad time, resulting in failure in a later `connect_nodes` call.\r\nAlso add the test with `--v2transport` to the test runner because banning with v2 seems like a useful thing to have test coverage for.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29372/comments",
   "created_at" : "2024-02-02T18:22:58Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29372/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/29372",
   "id" : 2115519182,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29372/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585l3QfN",
   "number" : 29372,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/29372.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29372",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/29372.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/29372"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29372/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29372/timeline",
   "title" : "test: fix intermittent failure in `rpc_setban.py --v2transport`, run it in CI",
   "updated_at" : "2024-02-02T18:25:05Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29372",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/48763452?v=4",
      "events_url" : "https://api.github.com/users/mzumsande/events{/privacy}",
      "followers_url" : "https://api.github.com/users/mzumsande/followers",
      "following_url" : "https://api.github.com/users/mzumsande/following{/other_user}",
      "gists_url" : "https://api.github.com/users/mzumsande/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/mzumsande",
      "id" : 48763452,
      "login" : "mzumsande",
      "node_id" : "MDQ6VXNlcjQ4NzYzNDUy",
      "organizations_url" : "https://api.github.com/users/mzumsande/orgs",
      "received_events_url" : "https://api.github.com/users/mzumsande/received_events",
      "repos_url" : "https://api.github.com/users/mzumsande/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/mzumsande/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/mzumsande/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/mzumsande"
   }
}
