[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@maflcko I'll continue our conversation here since https://github.com/bitcoin/bitcoin/pull/29395 was closed.\r\n\r\nI'm not sure if I understood your idea clearly. We would add a sleep in the source code than run the related functional tests to try to force a race condition, or is the issue within the functional tests themselves? Isn't the source of the issue clear yet for us to pin it down?\r\n\r\nIf you can point me in the right direction, I'll make some tweaking in the source code locally them post the results here for us to discuss.",
      "created_at" : "2024-02-08T17:04:21Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29392#issuecomment-1934559768",
      "id" : 1934559768,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29392",
      "node_id" : "IC_kwDOABII585zTwoY",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934559768/reactions"
      },
      "updated_at" : "2024-02-08T17:05:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934559768",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/46436462?v=4",
         "events_url" : "https://api.github.com/users/araujo88/events{/privacy}",
         "followers_url" : "https://api.github.com/users/araujo88/followers",
         "following_url" : "https://api.github.com/users/araujo88/following{/other_user}",
         "gists_url" : "https://api.github.com/users/araujo88/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/araujo88",
         "id" : 46436462,
         "login" : "araujo88",
         "node_id" : "MDQ6VXNlcjQ2NDM2NDYy",
         "organizations_url" : "https://api.github.com/users/araujo88/orgs",
         "received_events_url" : "https://api.github.com/users/araujo88/received_events",
         "repos_url" : "https://api.github.com/users/araujo88/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/araujo88/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/araujo88/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/araujo88"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> Isn't the source of the issue clear\r\n\r\nSo far I haven't seen the source of the issue.",
      "created_at" : "2024-02-08T17:20:46Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29392#issuecomment-1934598134",
      "id" : 1934598134,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29392",
      "node_id" : "IC_kwDOABII585zT5_2",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934598134/reactions"
      },
      "updated_at" : "2024-02-08T17:20:46Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934598134",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> If you can point me in the right direction\r\n\r\nI don't really think anyone has actually managed to reproduce the failure (i.e. managed to get the test fail locally with master in the same way it did in the failed CI run, possibly after putting a sleep somewhere). Or if you have managed that, you should describe what exactly you did. Therefore, at this point I don't think anyone knows the right direction, and the main part of solving this issue  - which is not necessarily easy -  is figuring that out somehow. Coming up with the right fix after that is often trivial in comparison.",
      "created_at" : "2024-02-08T20:05:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29392#issuecomment-1934853492",
      "id" : 1934853492,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29392",
      "node_id" : "IC_kwDOABII585zU4V0",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934853492/reactions"
      },
      "updated_at" : "2024-02-08T20:05:50Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934853492",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/48763452?v=4",
         "events_url" : "https://api.github.com/users/mzumsande/events{/privacy}",
         "followers_url" : "https://api.github.com/users/mzumsande/followers",
         "following_url" : "https://api.github.com/users/mzumsande/following{/other_user}",
         "gists_url" : "https://api.github.com/users/mzumsande/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/mzumsande",
         "id" : 48763452,
         "login" : "mzumsande",
         "node_id" : "MDQ6VXNlcjQ4NzYzNDUy",
         "organizations_url" : "https://api.github.com/users/mzumsande/orgs",
         "received_events_url" : "https://api.github.com/users/mzumsande/received_events",
         "repos_url" : "https://api.github.com/users/mzumsande/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/mzumsande/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/mzumsande/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/mzumsande"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> > If you can point me in the right direction\r\n> \r\n> I don't really think anyone has actually managed to reproduce the failure (i.e. managed to get the test fail locally with master in the same way it did in the failed CI run, possibly after putting a sleep somewhere). Or if you have managed that, you should describe what exactly you did. Therefore, at this point I don't think anyone knows the right direction, and the main part of solving this issue - which is not necessarily easy - is figuring that out somehow. Coming up with the right fix after that is often trivial in comparison.\r\n\r\nUnderstood. I'll try to reproduce the failure locally then report back here if I managed to pinpoint it.",
      "created_at" : "2024-02-08T20:40:25Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29392#issuecomment-1934899985",
      "id" : 1934899985,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29392",
      "node_id" : "IC_kwDOABII585zVDsR",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934899985/reactions"
      },
      "updated_at" : "2024-02-08T20:40:25Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934899985",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/46436462?v=4",
         "events_url" : "https://api.github.com/users/araujo88/events{/privacy}",
         "followers_url" : "https://api.github.com/users/araujo88/followers",
         "following_url" : "https://api.github.com/users/araujo88/following{/other_user}",
         "gists_url" : "https://api.github.com/users/araujo88/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/araujo88",
         "id" : 46436462,
         "login" : "araujo88",
         "node_id" : "MDQ6VXNlcjQ2NDM2NDYy",
         "organizations_url" : "https://api.github.com/users/araujo88/orgs",
         "received_events_url" : "https://api.github.com/users/araujo88/received_events",
         "repos_url" : "https://api.github.com/users/araujo88/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/araujo88/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/araujo88/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/araujo88"
      }
   }
]
