{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "`error(...)` has many issues:\r\n\r\n* It is often used in the context of `return error(...)`, implying that it has a \"fancy\" type, creating confusion with `util::Result/Error`\r\n* `-logsourcelocations` does not work with it, because it will pretend the error happened inside of `logging.h`\r\n* The log line contains `ERROR: `, as opposed to `[error]`, like for other errors logged with `LogError`.\r\n\r\nFix all issues by removing it.",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29236/comments",
   "created_at" : "2024-01-11T18:29:58Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29236/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/29236",
   "id" : 2077350644,
   "labels" : [
      {
         "color" : "5319e7",
         "default" : false,
         "description" : "",
         "id" : 241832923,
         "name" : "Utils/log/libs",
         "node_id" : "MDU6TGFiZWwyNDE4MzI5MjM=",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Utils/log/libs"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29236/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585j2G0b",
   "number" : 29236,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/29236.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29236",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/29236.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/29236"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29236/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29236/timeline",
   "title" : "log: Nuke error(...)",
   "updated_at" : "2024-01-11T20:06:01Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29236",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
      "followers_url" : "https://api.github.com/users/maflcko/followers",
      "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
      "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/maflcko",
      "id" : 6399679,
      "login" : "maflcko",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/maflcko/orgs",
      "received_events_url" : "https://api.github.com/users/maflcko/received_events",
      "repos_url" : "https://api.github.com/users/maflcko/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/maflcko"
   }
}
