[
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I can take a look at this.",
      "created_at" : "2023-12-25T12:34:05Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1868965467",
      "id" : 1868965467,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII585vZiZb",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1868965467/reactions"
      },
      "updated_at" : "2023-12-25T12:34:05Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1868965467",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/33068296?v=4",
         "events_url" : "https://api.github.com/users/dimitaracev/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dimitaracev/followers",
         "following_url" : "https://api.github.com/users/dimitaracev/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dimitaracev/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dimitaracev",
         "id" : 33068296,
         "login" : "dimitaracev",
         "node_id" : "MDQ6VXNlcjMzMDY4Mjk2",
         "organizations_url" : "https://api.github.com/users/dimitaracev/orgs",
         "received_events_url" : "https://api.github.com/users/dimitaracev/received_events",
         "repos_url" : "https://api.github.com/users/dimitaracev/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dimitaracev/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dimitaracev/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dimitaracev"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "The error seems to be: ` node0 stderr bitcoin-node: wallet/wallet.cpp:246: void wallet::UnloadWallet(std::shared_ptr<CWallet> &&): Assertion `it.second' failed. `?\r\n\r\nSo I think another bug would be that the error is not caught and reported by the python code?",
      "created_at" : "2023-12-25T13:34:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1868987998",
      "id" : 1868987998,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII585vZn5e",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1868987998/reactions"
      },
      "updated_at" : "2023-12-25T13:34:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1868987998",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Maybe we should return a proper message that indicates that the wallet we are trying to unload is already marked for unloading and we can catch that in the python code.",
      "created_at" : "2023-12-25T13:49:01Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1868993395",
      "id" : 1868993395,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII585vZpNz",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1868993395/reactions"
      },
      "updated_at" : "2023-12-25T13:49:01Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1868993395",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/33068296?v=4",
         "events_url" : "https://api.github.com/users/dimitaracev/events{/privacy}",
         "followers_url" : "https://api.github.com/users/dimitaracev/followers",
         "following_url" : "https://api.github.com/users/dimitaracev/following{/other_user}",
         "gists_url" : "https://api.github.com/users/dimitaracev/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/dimitaracev",
         "id" : 33068296,
         "login" : "dimitaracev",
         "node_id" : "MDQ6VXNlcjMzMDY4Mjk2",
         "organizations_url" : "https://api.github.com/users/dimitaracev/orgs",
         "received_events_url" : "https://api.github.com/users/dimitaracev/received_events",
         "repos_url" : "https://api.github.com/users/dimitaracev/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/dimitaracev/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/dimitaracev/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/dimitaracev"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "https://cirrus-ci.com/task/6533368603475968?logs=ci#L3401\r\n\r\n```\r\n node0 stderr bitcoin-node: wallet/wallet.cpp:246: void wallet::UnloadWallet(std::shared_ptr<CWallet> &&): Assertion `it.second' failed. ",
      "created_at" : "2024-02-08T18:04:36Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1934672607",
      "id" : 1934672607,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII585zUMLf",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934672607/reactions"
      },
      "updated_at" : "2024-02-08T18:04:36Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1934672607",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Added to 27.0, with the understanding that it is not a regression, and can be moved to 28.0, if needed.",
      "created_at" : "2024-02-22T18:08:28Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1959994612",
      "id" : 1959994612,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII58500yT0",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1959994612/reactions"
      },
      "updated_at" : "2024-02-22T18:08:28Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1959994612",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I'm not sure the two linked failures are necessarily the same failure. Both happen at different points in the test. The first is an assert failure during `Concurrent wallet loading` and the second is during `Load remaining wallets`.\r\n\r\nThe first appears to be a timing issue where perhaps an inconveniently timed database flush to disk slows down concurrent requests to load / unload the same wallet and all attempts succeed without hitting the loading mutex.\r\n\r\nIn the logs for the second occurrence we can see a broken pipe when trying to load a wallet. Flaky python rpc call?\r\n\r\nAlthough both do share the std error message complaining about `it.second` assertion I'm not convinced this is the cause for either of these failures. In the first test this assertion failure seems to come before the test has got to the concurrent wallet loading and in the second test the failure happens when trying to load a wallet, not unload it.\r\n\r\nI will see if I can get more information with the test running in a loop with `--tracerpc`.",
      "created_at" : "2024-03-11T15:49:49Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1988766390",
      "id" : 1988766390,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII5852iiq2",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1988766390/reactions"
      },
      "updated_at" : "2024-03-11T15:49:49Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1988766390",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1204616?v=4",
         "events_url" : "https://api.github.com/users/m3dwards/events{/privacy}",
         "followers_url" : "https://api.github.com/users/m3dwards/followers",
         "following_url" : "https://api.github.com/users/m3dwards/following{/other_user}",
         "gists_url" : "https://api.github.com/users/m3dwards/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/m3dwards",
         "id" : 1204616,
         "login" : "m3dwards",
         "node_id" : "MDQ6VXNlcjEyMDQ2MTY=",
         "organizations_url" : "https://api.github.com/users/m3dwards/orgs",
         "received_events_url" : "https://api.github.com/users/m3dwards/received_events",
         "repos_url" : "https://api.github.com/users/m3dwards/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/m3dwards/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/m3dwards/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/m3dwards"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Ran the test on the same i686 container as CI 1000 times without fail.\r\n\r\nFor the `Concurrent wallet loading` functional test, this depends on timing and therefore I believe will always have a chance of failing. Perhaps this should be a unit test only where hopefully you could have enough control to guarantee the mutex would be hit.\r\n\r\nMy only suggestion for the `Load remaining wallets` failure is to upgrade python from 3.10 to 3.12 which helped resolve some RPC connection issues for me previously.",
      "created_at" : "2024-03-12T09:55:27Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1991222766",
      "id" : 1991222766,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII5852r6Xu",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1991222766/reactions"
      },
      "updated_at" : "2024-03-12T09:55:27Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1991222766",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1204616?v=4",
         "events_url" : "https://api.github.com/users/m3dwards/events{/privacy}",
         "followers_url" : "https://api.github.com/users/m3dwards/followers",
         "following_url" : "https://api.github.com/users/m3dwards/following{/other_user}",
         "gists_url" : "https://api.github.com/users/m3dwards/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/m3dwards",
         "id" : 1204616,
         "login" : "m3dwards",
         "node_id" : "MDQ6VXNlcjEyMDQ2MTY=",
         "organizations_url" : "https://api.github.com/users/m3dwards/orgs",
         "received_events_url" : "https://api.github.com/users/m3dwards/received_events",
         "repos_url" : "https://api.github.com/users/m3dwards/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/m3dwards/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/m3dwards/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/m3dwards"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "The \"Assertion `it.second' failed.\" is a bug in the C++ source code. At least, I can't see how changing the python version would fix this. IIUC a broken pipe is expected when the program crashes, so I don't think this is a problem on the python side as well.",
      "created_at" : "2024-03-12T10:00:43Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1991237444",
      "id" : 1991237444,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII5852r99E",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1991237444/reactions"
      },
      "updated_at" : "2024-03-12T10:00:43Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1991237444",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "Ah ok, I made a wrong assumption there then. I assumed it could get hit if two requests to unload came at the same time but looking at the code again the lock two lines above should guard that.",
      "created_at" : "2024-03-12T10:09:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29073#issuecomment-1991255529",
      "id" : 1991255529,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29073",
      "node_id" : "IC_kwDOABII5852sCXp",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1991255529/reactions"
      },
      "updated_at" : "2024-03-12T10:09:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1991255529",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1204616?v=4",
         "events_url" : "https://api.github.com/users/m3dwards/events{/privacy}",
         "followers_url" : "https://api.github.com/users/m3dwards/followers",
         "following_url" : "https://api.github.com/users/m3dwards/following{/other_user}",
         "gists_url" : "https://api.github.com/users/m3dwards/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/m3dwards",
         "id" : 1204616,
         "login" : "m3dwards",
         "node_id" : "MDQ6VXNlcjEyMDQ2MTY=",
         "organizations_url" : "https://api.github.com/users/m3dwards/orgs",
         "received_events_url" : "https://api.github.com/users/m3dwards/received_events",
         "repos_url" : "https://api.github.com/users/m3dwards/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/m3dwards/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/m3dwards/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/m3dwards"
      }
   }
]
