[
   {
      "author_association" : "MEMBER",
      "body" : "Similar failure, different test: https://github.com/bitcoin/bitcoin/actions/runs/7249043694/job/19746211856#step:27:521.",
      "created_at" : "2023-12-18T15:03:45Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1860741967",
      "id" : 1860741967,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
      "node_id" : "IC_kwDOABII585u6KtP",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1860741967/reactions"
      },
      "updated_at" : "2023-12-18T15:03:45Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1860741967",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> Similar failure, different test: https://github.com/bitcoin/bitcoin/actions/runs/7249043694/job/19746211856#step:27:521.\r\n\r\nNot sure. This one has\r\n\r\n```\r\nError: 2023-12-18T14:15:31.391534Z [D:\\a\\bitcoin\\bitcoin\\src\\logging.h:264] [error] ERROR: Commit: Failed to commit latest txindex state \r\n```\r\n\r\nin the log.",
      "created_at" : "2024-01-24T09:31:14Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1907735929",
      "id" : 1907735929,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
      "node_id" : "IC_kwDOABII585xtb15",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1907735929/reactions"
      },
      "updated_at" : "2024-01-24T09:31:14Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1907735929",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "https://github.com/bitcoin/bitcoin/actions/runs/7667501768/job/20897463395\r\n\r\n```bash\r\n ============\r\nCombined log for D:\\a\\_temp/test_runner_â¿_ð_20240126_113602/feature_index_prune_293:\r\n============\r\n\r\n test  2024-01-26T11:36:28.165000Z TestFramework (INFO): PRNG seed is: 8852427722333217080 \r\n test  2024-01-26T11:36:28.165000Z TestFramework (DEBUG): Setting up network thread \r\n test  2024-01-26T11:36:28.212000Z TestFramework (INFO): Initializing test directory D:\\a\\_temp\\test_runner_â¿_ð_20240126_113602\\feature_index_prune_293 \r\n test  2024-01-26T11:36:28.212000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 0 \r\n test  2024-01-26T11:36:28.227000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 1 \r\n test  2024-01-26T11:36:28.274000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 2 \r\n test  2024-01-26T11:36:28.290000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 3 \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node3 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T12:18:05.036000Z TestFramework.node0 (DEBUG): Stopping node \r\n test  2024-01-26T12:18:05.036000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 556, in start_nodes\r\n                                       node.wait_for_rpc_connection()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 308, in wait_for_rpc_connection\r\n                                       self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 182, in _raise_assertion_error\r\n                                       raise AssertionError(self._node_msg(msg))\r\n                                   AssertionError: [node 0] Unable to connect to bitcoind after 2400s\r\n                                   During handling of the above exception, another exception occurred:\r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 130, in main\r\n                                       self.setup()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 297, in setup\r\n                                       self.setup_network()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 391, in setup_network\r\n                                       self.setup_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 413, in setup_nodes\r\n                                       self.start_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 559, in start_nodes\r\n                                       self.stop_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 574, in stop_nodes\r\n                                       node.stop_node(wait=wait, wait_until_stopped=False)\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 369, in stop_node\r\n                                       self.stop(wait=wait)\r\n                                       ^^^^^^^^^\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 199, in __getattr__\r\n                                       assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\n                                   AssertionError: [node 0] Error: no RPC connection\r\n test  2024-01-26T12:18:05.036000Z TestFramework (DEBUG): Closing down network thread \r\n test  2024-01-26T12:18:05.090000Z TestFramework (INFO): Stopping nodes \r\n test  2024-01-26T12:18:05.090000Z TestFramework.node0 (DEBUG): Stopping node \r\n````",
      "created_at" : "2024-01-26T13:25:32Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1912064796",
      "id" : 1912064796,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
      "node_id" : "IC_kwDOABII585x98sc",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1912064796/reactions"
      },
      "updated_at" : "2024-01-26T13:25:32Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1912064796",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
         "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
         "followers_url" : "https://api.github.com/users/fanquake/followers",
         "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
         "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/fanquake",
         "id" : 863730,
         "login" : "fanquake",
         "node_id" : "MDQ6VXNlcjg2MzczMA==",
         "organizations_url" : "https://api.github.com/users/fanquake/orgs",
         "received_events_url" : "https://api.github.com/users/fanquake/received_events",
         "repos_url" : "https://api.github.com/users/fanquake/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/fanquake"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "I have been unable to replicate this on my Windows 11 box after over 200 full suite runs.\r\n\r\nI did get a bunch of RPC timeouts when the tests tried to shut bitcoind down until I upgraded python from 3.11 to 3.12 and that seemed to fix that for me.\r\n\r\nThe CI job specifies python 3 (`py -3`) and on the hosted CI test runner since roughly October 2023 this will default to 3.12. No idea if this issue has anything to do with Python version but it's just to say all these failures would have been on the same version I am running stably. ",
      "created_at" : "2024-02-28T11:51:38Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1968819534",
      "id" : 1968819534,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
      "node_id" : "IC_kwDOABII5851Wc1O",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1968819534/reactions"
      },
      "updated_at" : "2024-02-28T11:51:38Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1968819534",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1204616?v=4",
         "events_url" : "https://api.github.com/users/m3dwards/events{/privacy}",
         "followers_url" : "https://api.github.com/users/m3dwards/followers",
         "following_url" : "https://api.github.com/users/m3dwards/following{/other_user}",
         "gists_url" : "https://api.github.com/users/m3dwards/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/m3dwards",
         "id" : 1204616,
         "login" : "m3dwards",
         "node_id" : "MDQ6VXNlcjEyMDQ2MTY=",
         "organizations_url" : "https://api.github.com/users/m3dwards/orgs",
         "received_events_url" : "https://api.github.com/users/m3dwards/received_events",
         "repos_url" : "https://api.github.com/users/m3dwards/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/m3dwards/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/m3dwards/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/m3dwards"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "> The CI job specifies python 3 (`py -3`) and on the hosted CI test runner since roughly October 2023 this will default to 3.12.\r\n\r\nI think it would be useful if the task printed the python version to the CI log, if that isn't already done.",
      "created_at" : "2024-02-28T11:57:04Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1968827963",
      "id" : 1968827963,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
      "node_id" : "IC_kwDOABII5851We47",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 1,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 1,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1968827963/reactions"
      },
      "updated_at" : "2024-02-28T11:57:04Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1968827963",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
         "followers_url" : "https://api.github.com/users/maflcko/followers",
         "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
         "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/maflcko",
         "id" : 6399679,
         "login" : "maflcko",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/maflcko/orgs",
         "received_events_url" : "https://api.github.com/users/maflcko/received_events",
         "repos_url" : "https://api.github.com/users/maflcko/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/maflcko"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "@hebasto also suggested printing the python version. I couldn't see it in the logs, I'll add it to the workflow.",
      "created_at" : "2024-02-28T12:07:43Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1968846214",
      "id" : 1968846214,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
      "node_id" : "IC_kwDOABII5851WjWG",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1968846214/reactions"
      },
      "updated_at" : "2024-02-28T12:07:43Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1968846214",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/1204616?v=4",
         "events_url" : "https://api.github.com/users/m3dwards/events{/privacy}",
         "followers_url" : "https://api.github.com/users/m3dwards/followers",
         "following_url" : "https://api.github.com/users/m3dwards/following{/other_user}",
         "gists_url" : "https://api.github.com/users/m3dwards/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/m3dwards",
         "id" : 1204616,
         "login" : "m3dwards",
         "node_id" : "MDQ6VXNlcjEyMDQ2MTY=",
         "organizations_url" : "https://api.github.com/users/m3dwards/orgs",
         "received_events_url" : "https://api.github.com/users/m3dwards/received_events",
         "repos_url" : "https://api.github.com/users/m3dwards/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/m3dwards/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/m3dwards/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/m3dwards"
      }
   }
]
