{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "Catching the exception in `AddCoin` and continuing will lead to the calculated memory usage of the cache to be out of sync (lower by the size of the existing coin). If we later remove more coins, this can lead to an underflow and the sanitizer will trip on a later overflow when we add back to `cachedCoinsUsage`. See https://github.com/bitcoin/bitcoin/pull/28216#issuecomment-1872991949.\r\n\r\nI found this while rebasing #28216 but another way of exposing this mistake is to simply run the cache sanity check after the `LIMITED_WHILE` loop. This PR fixes the underflow by not continuing when hitting this exception and adds the sanity check.\r\n\r\nThe crash can be reproduced with the following seed:\r\n```\r\nq6urNzc3NzfHx8fHx8fHx8fHx8cBpwAAAAD//wD/////7/+CAAAAAAAAAAGCgv9Z/////////8dDbwBcXW+XbyEhL01BTklGRVNULTAwMCEhBQUFBQUFBQX///////8hISMjIyP/ISHd//9rQ0P/AQAAISEhISMjIyP/ISHd//9rQ0MhISEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQAFBf8BAAAhISEhIyMjI/8hISEhISMjIyP/ISHd//9rQ0P/AQAAISEhISMjIyP/ISHd//9rQ0MhIUM/ISEhIf//////AH//////AQAAISEhISMjIyP/ISHd//9rQ0P/AQAAISEhISMjIyP/ISEhISEjIyMj/yEh3f//a0ND/wEAACEhISEjIyMj/yEh3f//a0NDISEhBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUABQUFBQUFx/9rQ0P/AQAAISEhISMjIyP/ISHd//9rQ0MhISEFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQAFBQUFBQXHx8fHx8fHx8fHx8fHxzc3Nzc3NzfHx8fHx8cFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFIf//ISEhISMjIyP/ISHd//////////////8x////////////ISHd//////////////8y/////+//////////////////f2vHx0ND/8fHxzc3Nzc3Nzc=\r\n```",
   "closed_at" : "2024-01-02T12:28:02Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/22457751?v=4",
      "events_url" : "https://api.github.com/users/darosior/events{/privacy}",
      "followers_url" : "https://api.github.com/users/darosior/followers",
      "following_url" : "https://api.github.com/users/darosior/following{/other_user}",
      "gists_url" : "https://api.github.com/users/darosior/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/darosior",
      "id" : 22457751,
      "login" : "darosior",
      "node_id" : "MDQ6VXNlcjIyNDU3NzUx",
      "organizations_url" : "https://api.github.com/users/darosior/orgs",
      "received_events_url" : "https://api.github.com/users/darosior/received_events",
      "repos_url" : "https://api.github.com/users/darosior/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/darosior/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/darosior/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/darosior"
   },
   "comments" : 6,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29164/comments",
   "created_at" : "2024-01-02T10:54:05Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29164/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/29164",
   "id" : 2062249200,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      },
      {
         "color" : "cccccc",
         "default" : false,
         "description" : "",
         "id" : 5334691551,
         "name" : "CI failed",
         "node_id" : "LA_kwDOABII588AAAABPfju3w",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29164/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585jCy_k",
   "number" : 29164,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/29164.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/29164",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/29164.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/29164"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29164/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29164/timeline",
   "title" : "fuzz: avoid underflow in `coins_view` target",
   "updated_at" : "2024-01-02T12:28:02Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29164",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/22457751?v=4",
      "events_url" : "https://api.github.com/users/darosior/events{/privacy}",
      "followers_url" : "https://api.github.com/users/darosior/followers",
      "following_url" : "https://api.github.com/users/darosior/following{/other_user}",
      "gists_url" : "https://api.github.com/users/darosior/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/darosior",
      "id" : 22457751,
      "login" : "darosior",
      "node_id" : "MDQ6VXNlcjIyNDU3NzUx",
      "organizations_url" : "https://api.github.com/users/darosior/orgs",
      "received_events_url" : "https://api.github.com/users/darosior/received_events",
      "repos_url" : "https://api.github.com/users/darosior/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/darosior/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/darosior/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/darosior"
   }
}
