{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "Without the sync, the logic will be racy. For example, `p2p_sendtxrcncl.py` is failing locally (and on CI occasionally), because non-version messages will be sent before the version message:\r\n\r\n\r\n```py\r\n        self.log.info('SENDTXRCNCL with version=0 triggers a disconnect')\r\n        sendtxrcncl_low_version = create_sendtxrcncl_msg()\r\n        sendtxrcncl_low_version.version = 0\r\n        peer = self.nodes[0].add_p2p_connection(PeerNoVerack(), send_version=True, wait_for_verack=False)\r\n        with self.nodes[0].assert_debug_log([\"txreconciliation protocol violation\"]):\r\n            peer.send_message(sendtxrcncl_low_version)\r\n            peer.wait_for_disconnect()\r\n```\r\n\r\n```\r\n test  2023-11-02T08:15:19.620000Z TestFramework (INFO): SENDTXRCNCL with version=0 triggers a disconnect \r\n test  2023-11-02T08:15:19.621000Z TestFramework.p2p (DEBUG): Connecting to Bitcoin Node: 127.0.0.1:11312 \r\n test  2023-11-02T08:15:19.624000Z TestFramework.p2p (DEBUG): Connected & Listening: 127.0.0.1:11312 \r\n test  2023-11-02T08:15:19.798000Z TestFramework.p2p (DEBUG): Send message to 127.0.0.1:11312: msg_sendtxrcncl(version=0, salt=2) \r\n test  2023-11-02T08:15:19.799000Z TestFramework.p2p (DEBUG): Send message to 127.0.0.1:11312: msg_version(nVersion=70016 nServices=9 nTime=Thu Nov  2 08:15:19 2023 addrTo=CAddress(nServices=1 net=IPv4 addr=127.0.0.1 port=11312) addrFrom=CAddress(nServices=1 net=IPv4 addr=0.0.0.0 port=0) nNonce=0x369AC031CDA96022 strSubVer=/python-p2p-tester:0.0.3/ nStartingHeight=-1 relay=1) \r\n node0 2023-11-02T08:15:19.804409Z [net] [net.cpp:3676] [CNode] [net] Added connection peer=0 \r\n node0 2023-11-02T08:15:19.805256Z [net] [net.cpp:1825] [CreateNodeFromAcceptedSocket] [net] connection from 127.0.0.1:55964 accepted \r\n node0 2023-11-02T08:15:19.809861Z [msghand] [net_processing.cpp:3356] [ProcessMessage] [net] received: sendtxrcncl (12 bytes) peer=0 \r\n node0 2023-11-02T08:15:19.810297Z [msghand] [net_processing.cpp:3582] [ProcessMessage] [net] non-version message before version handshake. Message \"sendtxrcncl\" from peer=0 \r\n node0 2023-11-02T08:15:19.810928Z [msghand] [net_processing.cpp:3356] [ProcessMessage] [net] received: version (111 bytes) peer=0 \r\n...\r\n test  2023-11-02T09:35:20.166000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' \r\n                                           def test_function():\r\n                                               if check_connected:\r\n                                                   assert self.is_connected\r\n                                               return test_function_in()\r\n                                   '''\r\n test  2023-11-02T09:35:20.187000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-s390x-linux-gnu/test/functional/test_framework/test_framework.py\", line 132, in main\r\n                                       self.run_test()\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-s390x-linux-gnu/test/functional/p2p_sendtxrcncl.py\", line 188, in run_test\r\n                                       peer.wait_for_disconnect()\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-s390x-linux-gnu/test/functional/test_framework/p2p.py\", line 478, in wait_for_disconnect\r\n                                       self.wait_until(test_function, timeout=timeout, check_connected=False)\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-s390x-linux-gnu/test/functional/test_framework/p2p.py\", line 470, in wait_until\r\n                                       wait_until_helper_internal(test_function, timeout=timeout, lock=p2p_lock, timeout_factor=self.timeout_factor)\r\n                                     File \"/ci_container_base/ci/scratch/build/bitcoin-s390x-linux-gnu/test/functional/test_framework/util.py\", line 275, in wait_until_helper_internal\r\n                                       raise AssertionError(\"Predicate {} not true after {} seconds\".format(predicate_source, timeout))\r\n                                   AssertionError: Predicate ''''\r\n                                           def test_function():\r\n                                               if check_connected:\r\n                                                   assert self.is_connected\r\n                                               return test_function_in()\r\n                                   ''' not true after 4800.0 seconds\r\n",
   "closed_at" : null,
   "closed_by" : null,
   "comments" : 1,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28782/comments",
   "created_at" : "2023-11-03T12:30:25Z",
   "draft" : false,
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28782/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/pull/28782",
   "id" : 1976096672,
   "labels" : [
      {
         "color" : "d4c5f9",
         "default" : false,
         "description" : null,
         "id" : 62963516,
         "name" : "Tests",
         "node_id" : "MDU6TGFiZWw2Mjk2MzUxNg==",
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests"
      }
   ],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28782/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "PR_kwDOABII585eiCc2",
   "number" : 28782,
   "performed_via_github_app" : null,
   "pull_request" : {
      "diff_url" : "https://github.com/bitcoin/bitcoin/pull/28782.diff",
      "html_url" : "https://github.com/bitcoin/bitcoin/pull/28782",
      "merged_at" : null,
      "patch_url" : "https://github.com/bitcoin/bitcoin/pull/28782.patch",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/pulls/28782"
   },
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28782/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "open",
   "state_reason" : null,
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28782/timeline",
   "title" : "test: Add missing sync on send_version in peer_connect",
   "updated_at" : "2023-11-03T14:53:57Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/28782",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
      "events_url" : "https://api.github.com/users/maflcko/events{/privacy}",
      "followers_url" : "https://api.github.com/users/maflcko/followers",
      "following_url" : "https://api.github.com/users/maflcko/following{/other_user}",
      "gists_url" : "https://api.github.com/users/maflcko/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/maflcko",
      "id" : 6399679,
      "login" : "maflcko",
      "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
      "organizations_url" : "https://api.github.com/users/maflcko/orgs",
      "received_events_url" : "https://api.github.com/users/maflcko/received_events",
      "repos_url" : "https://api.github.com/users/maflcko/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/maflcko/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/maflcko/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/maflcko"
   }
}
